### ISSUE TITLE
WIFI icons not visible in light mode macOS Mojave

### ISSUE THREAD

**Issue by chris1111** [yunyu/OSXRealtekWifiIcons#2]
I test your icons in Mojave but is not visible in light mode only visible in Dak Mode

**Comment by yunyu** [comment]
Use `icons`, not `mojave-icons`.

**Comment by chris1111** [comment]
Ya right!  Now the wifi icons is not visible in dark mode 🤭

**Comment by yunyu** [comment]
I don't use macOS anymore, not sure how to support auto night mode. Feel free to submit a PR!

**Comment by chris1111** [comment]
Ok I try different collor, this set of icons works in both mode light and dark
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu425.png)
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu426.png)
attaching here my test icons
[Wifi-Iconset.zip](https://github.com/yunyu/OSXRealtekWifiIcons/files/2718616/Wifi-Iconset.zip)

**Comment by zb2947244682** [comment]
very thank you~~
